/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author felilein
 */
public class SwingGui extends javax.swing.JFrame {

    /**
     * Creates new form SwingGui
     */
    public SwingGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupToolbar = new javax.swing.ButtonGroup();
        jDialogCreate = new javax.swing.JDialog();
        jTabbedPaneCreate = new javax.swing.JTabbedPane();
        jPanelCreateBook = new javax.swing.JPanel();
        jTextFieldBook = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelCreateChapter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxBook = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldChapter = new javax.swing.JTextField();
        jPanelCreatePage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxBook2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPage = new javax.swing.JTextField();
        jComboBoxChapter = new javax.swing.JComboBox();
        jButtonCreate = new javax.swing.JButton();
        jDialogError = new javax.swing.JDialog();
        jLabelError = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaErrorMessage = new javax.swing.JTextArea();
        jButtonClose = new javax.swing.JButton();
        jDialogRename = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNewName = new javax.swing.JTextField();
        jButtonRenameNow = new javax.swing.JButton();
        jToolBarTools = new javax.swing.JToolBar();
        jToggleButtonCurser = new javax.swing.JToggleButton();
        jToggleButtonText = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButtonNew = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonRename = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPanePage = new javax.swing.JScrollPane();
        jPanelPage = new javax.swing.JPanel();
        jToolBarTool = new javax.swing.JToolBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuData = new javax.swing.JMenu();
        jMenuItemPrint = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemUndo = new javax.swing.JMenuItem();
        jMenuItemRedo = new javax.swing.JMenuItem();
        jMenuItemSearch = new javax.swing.JMenuItem();
        jMenuImport = new javax.swing.JMenu();
        jMenuItemImportPdf = new javax.swing.JMenuItem();
        jMenuItemImportPicture = new javax.swing.JMenuItem();
        jMenuExport = new javax.swing.JMenu();
        jMenuItemExportPdf = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemStartpage = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jDialogCreate.setTitle("Erstellen");
        jDialogCreate.setMinimumSize(new java.awt.Dimension(390, 315));
        jDialogCreate.setResizable(false);

        jTabbedPaneCreate.setBackground(new java.awt.Color(254, 254, 254));

        jTextFieldBook.setText("neues Buch");

        jLabel1.setText("Name:");

        javax.swing.GroupLayout jPanelCreateBookLayout = new javax.swing.GroupLayout(jPanelCreateBook);
        jPanelCreateBook.setLayout(jPanelCreateBookLayout);
        jPanelCreateBookLayout.setHorizontalGroup(
            jPanelCreateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateBookLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldBook)
                .addGap(41, 41, 41))
        );
        jPanelCreateBookLayout.setVerticalGroup(
            jPanelCreateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateBookLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelCreateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBook)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPaneCreate.addTab("Buch erstellen", jPanelCreateBook);

        jLabel2.setText("Buch:");

        jLabel3.setText("Name:");

        jTextFieldChapter.setText("neues Kapitel");

        javax.swing.GroupLayout jPanelCreateChapterLayout = new javax.swing.GroupLayout(jPanelCreateChapter);
        jPanelCreateChapter.setLayout(jPanelCreateChapterLayout);
        jPanelCreateChapterLayout.setHorizontalGroup(
            jPanelCreateChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateChapterLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelCreateChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanelCreateChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldChapter, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jComboBoxBook, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanelCreateChapterLayout.setVerticalGroup(
            jPanelCreateChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateChapterLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelCreateChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelCreateChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPaneCreate.addTab("Kapitel erstellen", jPanelCreateChapter);

        jLabel4.setText("Buch:");

        jComboBoxBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBook2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Kapitel:");

        jLabel6.setText("Seite:");

        jTextFieldPage.setText("neue Seite");

        javax.swing.GroupLayout jPanelCreatePageLayout = new javax.swing.GroupLayout(jPanelCreatePage);
        jPanelCreatePage.setLayout(jPanelCreatePageLayout);
        jPanelCreatePageLayout.setHorizontalGroup(
            jPanelCreatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreatePageLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelCreatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanelCreatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxChapter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxBook2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPage, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanelCreatePageLayout.setVerticalGroup(
            jPanelCreatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreatePageLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelCreatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBook2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelCreatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelCreatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPage)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jTabbedPaneCreate.addTab("Seite erstellen", jPanelCreatePage);

        jButtonCreate.setText("Erstellen");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogCreateLayout = new javax.swing.GroupLayout(jDialogCreate.getContentPane());
        jDialogCreate.getContentPane().setLayout(jDialogCreateLayout);
        jDialogCreateLayout.setHorizontalGroup(
            jDialogCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCreate)
            .addGroup(jDialogCreateLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        jDialogCreateLayout.setVerticalGroup(
            jDialogCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCreateLayout.createSequentialGroup()
                .addComponent(jTabbedPaneCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCreate)
                .addContainerGap())
        );

        jDialogError.setMinimumSize(new java.awt.Dimension(513, 252));
        jDialogError.setResizable(false);

        jLabelError.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelError.setText("jLabel7");

        jTextAreaErrorMessage.setEditable(false);
        jTextAreaErrorMessage.setColumns(20);
        jTextAreaErrorMessage.setRows(5);
        jScrollPane3.setViewportView(jTextAreaErrorMessage);

        jButtonClose.setText("Schließen");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogErrorLayout = new javax.swing.GroupLayout(jDialogError.getContentPane());
        jDialogError.getContentPane().setLayout(jDialogErrorLayout);
        jDialogErrorLayout.setHorizontalGroup(
            jDialogErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogErrorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jDialogErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogErrorLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        jDialogErrorLayout.setVerticalGroup(
            jDialogErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogErrorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonClose)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jDialogRename.setTitle("Umbenennen");
        jDialogRename.setMinimumSize(new java.awt.Dimension(354, 176));
        jDialogRename.setResizable(false);
        jDialogRename.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogRenameWindowClosing(evt);
            }
        });

        jLabel7.setText("Neuer Name:");

        jButtonRenameNow.setText("Umbenennen");
        jButtonRenameNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameNowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogRenameLayout = new javax.swing.GroupLayout(jDialogRename.getContentPane());
        jDialogRename.getContentPane().setLayout(jDialogRenameLayout);
        jDialogRenameLayout.setHorizontalGroup(
            jDialogRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRenameLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jDialogRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRenameNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogRenameLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jDialogRenameLayout.setVerticalGroup(
            jDialogRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRenameLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jDialogRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNewName)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRenameNow)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TwoNote");

        jToolBarTools.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBarTools.setFloatable(false);
        jToolBarTools.setRollover(true);

        buttonGroupToolbar.add(jToggleButtonCurser);
        jToggleButtonCurser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/curserBild.png"))); // NOI18N
        jToggleButtonCurser.setSelected(true);
        jToggleButtonCurser.setText("Zeiger");
        jToggleButtonCurser.setFocusable(false);
        jToggleButtonCurser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonCurser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonCurser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCurserActionPerformed(evt);
            }
        });
        jToolBarTools.add(jToggleButtonCurser);

        buttonGroupToolbar.add(jToggleButtonText);
        jToggleButtonText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/textBild.png"))); // NOI18N
        jToggleButtonText.setText("Text");
        jToggleButtonText.setFocusable(false);
        jToggleButtonText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonText.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTextActionPerformed(evt);
            }
        });
        jToolBarTools.add(jToggleButtonText);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Meine Notizen");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mathematik");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Analysis");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Lineare Algebra");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Informatik");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("C");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("C++");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setDragEnabled(true);
        jTree1.setDropMode(javax.swing.DropMode.ON_OR_INSERT);
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTree1MousePressed(evt);
            }
        });
        jTree1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTree1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jButtonNew.setText("Neu...");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Löschen");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonRename.setText("Umbenennen");
        jButtonRename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameActionPerformed(evt);
            }
        });

        jScrollPanePage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelPageMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelPageMouseReleased(evt);
            }
        });
        jPanelPage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelPageMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanelPageLayout = new javax.swing.GroupLayout(jPanelPage);
        jPanelPage.setLayout(jPanelPageLayout);
        jPanelPageLayout.setHorizontalGroup(
            jPanelPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        jPanelPageLayout.setVerticalGroup(
            jPanelPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jScrollPanePage.setViewportView(jPanelPage);

        jTabbedPane1.addTab("Startseite", jScrollPanePage);

        jToolBarTool.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBarTool.setFloatable(false);
        jToolBarTool.setRollover(true);

        jMenuData.setText("Datei");

        jMenuItemPrint.setText("Drucken");
        jMenuItemPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItemPrint);

        jMenuItemExit.setText("Beenden");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItemExit);

        jMenuBar1.add(jMenuData);

        jMenuEdit.setText("Bearbeiten");

        jMenuItemUndo.setText("Rückgängig");
        jMenuItemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUndoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemUndo);

        jMenuItemRedo.setText("Wiederherstellen");
        jMenuItemRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRedoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemRedo);

        jMenuItemSearch.setText("Suchen");
        jMenuItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemSearch);

        jMenuBar1.add(jMenuEdit);

        jMenuImport.setText("Importieren");

        jMenuItemImportPdf.setText("PDF importieren");
        jMenuItemImportPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportPdfActionPerformed(evt);
            }
        });
        jMenuImport.add(jMenuItemImportPdf);

        jMenuItemImportPicture.setText("Bild importieren");
        jMenuItemImportPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportPictureActionPerformed(evt);
            }
        });
        jMenuImport.add(jMenuItemImportPicture);

        jMenuBar1.add(jMenuImport);

        jMenuExport.setText("Exportieren");

        jMenuItemExportPdf.setText("Als PDF exportieren");
        jMenuItemExportPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExportPdfActionPerformed(evt);
            }
        });
        jMenuExport.add(jMenuItemExportPdf);

        jMenuBar1.add(jMenuExport);

        jMenuHelp.setText("Hilfe");

        jMenuItemStartpage.setText("Startseite");
        jMenuItemStartpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStartpageActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemStartpage);

        jMenuItemAbout.setText("Information");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTabbedPane1)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRename, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBarTools, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToolBarTool, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBarTools, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBarTool, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRename)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUndoActionPerformed

    private void jMenuItemPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPrintActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemStartpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStartpageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemStartpageActionPerformed

    private void jMenuItemExportPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExportPdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemExportPdfActionPerformed

    private void jMenuItemImportPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportPictureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemImportPictureActionPerformed

    private void jMenuItemImportPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportPdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemImportPdfActionPerformed

    private void jMenuItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSearchActionPerformed

    private void jMenuItemRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRedoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRedoActionPerformed

    private void jToggleButtonCurserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCurserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonCurserActionPerformed

    private void jToggleButtonTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonTextActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        jDialogCreate.setVisible(true);
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameActionPerformed
        jDialogRename.setVisible(true);
    }//GEN-LAST:event_jButtonRenameActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        jDialogError.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jComboBoxBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBook2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBook2ActionPerformed

    private void jTree1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1MousePressed

    private void jButtonRenameNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameNowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRenameNowActionPerformed

    private void jDialogRenameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogRenameWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogRenameWindowClosing

    private void jPanelPageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPageMousePressed
        System.err.println("Mouse Pressed");
    }//GEN-LAST:event_jPanelPageMousePressed

    private void jPanelPageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPageMouseReleased
        System.err.println("Mouse Released");
    }//GEN-LAST:event_jPanelPageMouseReleased

    private void jTree1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTree1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1KeyPressed

    private void jPanelPageMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPageMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelPageMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupToolbar;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCreate;
    protected javax.swing.JButton jButtonDelete;
    protected javax.swing.JButton jButtonNew;
    protected javax.swing.JButton jButtonRename;
    private javax.swing.JButton jButtonRenameNow;
    private javax.swing.JComboBox jComboBoxBook;
    private javax.swing.JComboBox jComboBoxBook2;
    private javax.swing.JComboBox jComboBoxChapter;
    private javax.swing.JDialog jDialogCreate;
    private javax.swing.JDialog jDialogError;
    private javax.swing.JDialog jDialogRename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelError;
    protected javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuData;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuExport;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenu jMenuImport;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemExportPdf;
    private javax.swing.JMenuItem jMenuItemImportPdf;
    private javax.swing.JMenuItem jMenuItemImportPicture;
    private javax.swing.JMenuItem jMenuItemPrint;
    private javax.swing.JMenuItem jMenuItemRedo;
    private javax.swing.JMenuItem jMenuItemSearch;
    private javax.swing.JMenuItem jMenuItemStartpage;
    private javax.swing.JMenuItem jMenuItemUndo;
    private javax.swing.JPanel jPanelCreateBook;
    private javax.swing.JPanel jPanelCreateChapter;
    private javax.swing.JPanel jPanelCreatePage;
    protected javax.swing.JPanel jPanelPage;
    protected javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    protected javax.swing.JScrollPane jScrollPanePage;
    protected javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneCreate;
    private javax.swing.JTextArea jTextAreaErrorMessage;
    private javax.swing.JTextField jTextFieldBook;
    private javax.swing.JTextField jTextFieldChapter;
    private javax.swing.JTextField jTextFieldNewName;
    private javax.swing.JTextField jTextFieldPage;
    protected javax.swing.JToggleButton jToggleButtonCurser;
    protected javax.swing.JToggleButton jToggleButtonText;
    protected javax.swing.JToolBar jToolBarTool;
    protected javax.swing.JToolBar jToolBarTools;
    protected javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
